### ISSUE TITLE
Enable debugger support

### ISSUE THREAD

**Issue by avaer** [exokitxr/libnode.a#1]
This is disabled in `0.0.1`.

```
09-15 23:46:58.807  1968     6 I exokit  : Inspector support is not available with this Node.js build
09-15 23:46:58.807  1968     6 I exokit  : node: bad option: --inspect
09-15 23:46:58.807  1968     6 I exokit  : node: bad option: --debug-brk```
```

Currently I see no reason why it couldn't be enabled.

**Comment by machenmusik** [comment]
If there are security concerns, perhaps the capability can be enabled (built in) but it could still require explicit passing of the proper command line flags to be activated.

**Comment by avaer** [comment]
I agree, but I don't think the reason for this disabling was security. It was some silly technical thing.

Moved to https://github.com/webmixedreality/exokit/issues/486.
